---
- name: Playbook to add multiple users and groups using nested loops
  hosts: node1
  become: true
  tasks:
    - name: Adding the groups.
      group:
              name: "{{ item }}"
              state: present
      with_items:
              - student
              - teacher
              - scholar
    - name: Adding local user accounts.
      user:
        name: "{{ item[0] }}"
        groups: "{{ item[1] }}"
        append: yes
      with_nested:
        - { vijay, sanju, neha, lara }
        - { student, teacher, scholar }
...

