---
- name: Install Apache on RHEL server
  hosts: node1
  become: true
  tasks:
    - name: Install the latest version of Apache
      dnf:
        name: httpd
        state: latest
      notify:
        - Start Apache

  handlers:
      - name: Start Apache
        service:
          name: httpd
          state: started
...
