---
- name: Example of listing type playbook variables.
  hosts: RHEL
  become: true
  vars:
    mypkgs:
      - ftp
      - vsftpd
      - zsh
  tasks:
    - name: Installing the packages.
      yum:
        name: "{{ mypkgs }}"
        state: installed
...
