---
- name: Ansible standard loop playbook to add user accounts with admin access
  hosts: RHEL
  vars_files:
    - /home/vikasnehra/users.yml
  become: true
  tasks:
    - name: Adding user accounts with admin access
      user:
        name: "{{ item }}"
        state: present
        group: wheel
      with_items:
        - "{{ users }}"
...
